name: forsencode_dart
description: An implementation of ForsenCode in Dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   string_validator: '0.3.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
